- name: Deploy Glances
  community.docker.docker_container:
    name: glances
    image: nicolargo/glances
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    pid_mode: host
    ports:
      - "61208:61208"
      - "61209:61209"
    env:
      GLANCES_OPT: "-w"
      TZ: "{{ timezone }}"
    restart_policy: always
