- name: Deploy nextcloud-mariadb
  community.docker.docker_container:
    name: nextcloud-mariadb
    image: mariadb
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed --innodb-read-only-compressed=OFF"
    volumes:
      - "{{ docker_dir }}/nextcloud/db:/var/lib/mysql"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      TZ: "{{ timezone }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
    restart_policy: unless-stopped


- name: Deploy nextcloud
  community.docker.docker_container:
    name: nextcloud
    image: nextcloud
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      TZ: "{{ timezone }}"
      ServerName: "{{ ansible_hostname }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_HOST: "nextcloud-mariadb"
    volumes:
      - "{{ docker_dir }}/nextcloud/nextcloud:/var/www/html"
    ports:
      - "8008:80/tcp"
    links:
      - nextcloud-mariadb
    restart_policy: unless-stopped
