- name: Playbook to manage all infra
  hosts: homelab

  roles:
    # System configuration
    # - system/init
    # - system/ssh
    # - system/timezone

    # Update and install basic packages
    # - system/packages
    # - system/upgrade

    # Setup dnf autoupdate
    # - system/dnfautomatic # Install automatic updates

    # Network configuration
    # - network/firewalld

    # Network filesystem
    # - system/nfs

    # Install docker
    # - role: geerlingguy.docker
    #   become: true

    # Setup containers

    # Filesystem
    # - containers/fs

    # System
    # - containers/portainer
    - containers/watchtower
    # - containers/pihole
    # - containers/nginx
    # - containers/homer

    # Monitoring
    # - containers/netdata
    # - containers/glances

    # Media / Storage
    # - containers/plex
    # - containers/nextcloud
    # - containers/photoprism

    # Home automation
    # - containers/homeassistant
