- name: Playbook to manage all infra
  hosts: homelab

  roles:
    # System configuration
    # - system/users
    # - system/ssh
    # - system/timezone

    # Update and install basic packages
    - system/packages
    - system/upgrade

    # Setup dnf autoupdate
    # - system/dnfautomatic # Install automatic updates

    # Network configuration
    # - network/firewalld

    # # Install docker
    # - role: geerlingguy.docker
    #   become: true

    # Setup containers
    # - containers/fs
    # - containers/portainer
    # - containers/watchtower
    # - containers/pihole
    # - containers/nginx
    # - containers/homer
    # - containers/plex
