- name: Playbook to manage all infra
  hosts: homelab

  roles:
    # Add default user
    # - users

    # Configure ssh
    # - ssh

    # Update and install basic packages
    # - packages
    # - upgrade

    # # Install docker
    # - role: geerlingguy.docker
    #   become: true

    # Services
    # - services/dnfautomatic
    # - services/firewalld

    # Containers
    # - containers/portainer
    - containers/watchtower
