- name: Playbook to manage all infra
  hosts: homelab

  roles:
    # System setup
    # - timezone  # Set timezone
    # - users     # Add default user
    # - ssh       # Configure ssh

    # Update and install basic packages
    # - packages
    # - upgrade

    # # Install docker
    # - role: geerlingguy.docker
    #   become: true


    # Services
    # - services/dnfautomatic
    # - services/firewalld

    # Containers
    - containers/fs
    - containers/portainer
    - containers/watchtower
    - containers/homer
    # - containers/pihole
