- name: Playbook to manage all infra
  hosts: homelab

  roles:
    # Add default user
    # - users

    # Configure ssh
    # - ssh

    # Update and install basic packages
    - packages
    - upgrade

    # Services
    - services/dnfautomatic
    - services/firewalld

    # # Install docker
    # - role: geerlingguy.docker
    #   become: true
