- name: Playbook to manage all infra
  hosts: homelab

  roles:
    # System configuration
    # - system/users        # Add default user
    # - system/ssh          # Configure ssh
    # - system/timezone     # Set timezone

    # Update and install basic packages
    - system/packages       # Install packages
    - system/upgrade        # Upgrade package

    # Setup dnf autoupdate
    # - system/dnfautomatic # Install automatic updates

    # Network configuration
    # - network/firewalld

    # # Install docker
    # - role: geerlingguy.docker
    #   become: true

    # Setup containers
    # - containers/fs
    # - containers/portainer
    # - containers/watchtower
    # - containers/homer
    # - containers/pihole
