- name: Playbook to manage all infra
  hosts: homelab

  roles:
    # Add default user
    # - users
    # - ssh

    - packages
    - upgrade

    # Install docker
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - "{{ docker_user }}"
