- name: Playbook to manage all infra
  hosts: homelab

  roles:
    # Update and install basic packages
    # - system/packages
    # - system/upgrade

    # Network configuration
    # - network/avahi-daemon

    # Network filesystem
    # - system/mount

    # Install docker
    # - role: geerlingguy.docker
    #   become: true

    # Server
    # - containers/server/portainer
    # - containers/server/watchtower
    # - containers/server/homer

    # Monitoring
    # - containers/monitoring/glances
    # - containers/monitoring/netdata
    - containers/monitoring/prometheus

    # Media / Storage
    # - containers/media/plex
    # - containers/media/nextcloud
    # - containers/media/photoprism
    # - containers/media/transmission
    # - containers/media/freshrss
    # - containers/media/syncthing
    # - containers/media/gitea

    # Home automation
    # - containers/automation/homeassistant
    # - containers/automation/homebridge

    # Munin
    # - system/munin
