- name: Playbook to manage all infra
  hosts: homelab

  roles:
    - users
    - upgrade
    - packages
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          lento
