- name: Deploy transmission
  community.docker.docker_container:
    name: transmission
    image: lscr.io/linuxserver/transmission:latest
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      TZ: "{{ timezone }}"
      TRANSMISSION_WEB_HOME: "/combustion-release/"
    volumes:
      - "{{ docker_dir }}/transmission:/config"
      - "{{ media_dir }}:/downloads"
      - "{{ media_dir }}/watch:/watch"
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart_policy: unless-stopped
