- name: Check if the persistent data folder exists
  ansible.builtin.stat:
    path: "{{ docker_dir }}"
  register: persistent_data

- name: Create the persistent data folder for docker containers
  become: true
  ansible.builtin.file:
    dest: "{{ docker_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    recurse: true
  when: not persistent_data.stat.exists
