- name: Add group {{ group }}
  become: true
  group:
    name: "{{ group }}"
    gid: "{{ guid }}"
    state: present

- name: Add user {{ user }}
  become: true
  user:
    name: "{{ user }}"
    uid: "{{ uid }}"
    shell: "{{ shell }}"
    password: "{{ password | password_hash('sha512') }}"
    group: "{{ group }}"
    groups:
      - "{{ sudo_group }}"
    append: true
