- name: Deploy nginx proxy manager
  community.docker.docker_container:
    name: nginx
    image: jc21/nginx-proxy-manager
    ports:
      - "80:80"
      - "443:443"
      - "8888:81"
    volumes:
      - "{{ docker_dir }}/nginx/data:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: always

- name: Create the persistent custom folder for nginx
  become: true
  ansible.builtin.file:
    dest: "{{ docker_dir }}/nginx/data/nginx/custom"
    state: directory
    mode: 0755

- name: Copy custom proxy configuration to nginx
  become: true
  ansible.builtin.template:
    src: http.conf.j2
    dest: "{{ docker_dir }}/nginx/data/nginx/custom/http.conf"
    mode: "0644"
  notify: Restart nginx
