- name: Setup basic dnf packages and config
  become: true
  dnf:
    update_cache: true
    name:
      - e2fsprogs
      - epel-release
      - git
      - zsh
    enablerepo:
      - epel
    state: latest

- name: Add group {{ group }}
  become: true
  group:
    name: "{{ group }}"
    gid: "{{ gid }}"
    state: present

- name: Add user {{ user }}
  become: true
  user:
    name: "{{ user }}"
    uid: "{{ uid }}"
    shell: "{{ shell }}"
    password: "{{ password | password_hash('sha512') }}"
    group: "{{ group }}"
    groups:
      - "{{ sudo_group }}"
    append: true
