# User settings
user: lento
group: "{{ user }}"
uid: 1001
gid: 1001
shell: /bin/zsh
sudo_group: wheel

# Install packages
packages:
  - curl
  - git
  - htop
  - neofetch
  - nginx
  - nmap
  - rsync
  - tmux
  - tree
  - wget
  - zsh

# Docker
docker_users:
  - "{{ user }}"

# Secrets in vault.yml
password: ''
