# User settings
uid: "1000"
gid: "1000"
shell: /bin/zsh
sudo_group: wheel

# NAS
nas:
  hostname: ohara
  address: 10.0.0.123
  store_dir: /mnt/zpool/store
  share_dir: share

# Locale
timezone: Europe/Zurich
domain_name: local

# Install packages
packages:
  - curl
  - git
  - htop
  - neofetch
  - nmap
  - python3-pip
  - rsync
  - tmux
  - tree
  - wget
  - zsh

# Install python packages
python_packages:
  - pip
  - pipx

# Install user python packages
python_user_packages:
  - docker
  - docker-compose

# Docker
docker_users:
  - "{{ user }}"

# Docker volumes
docker_dir: "/mnt/data/docker"

# Media directories
media_dir: "/mnt/data/media"
tv_dir: "{{ media_dir }}/tv"
movies_dir: "{{ media_dir }}/movies"

# Ports (tcp, udp)
ports:
  # - 22/tcp    # ssh (disabled)
  - 53/tcp    # dns (pi-hole)
  - 53/udp    # dns (pi-hole)
  - 80/tcp    # http
  - 81/tcp    # pi-hole dashboard
  - 443/tcp   # https
  - 1900/udp  # Plex DLNA Server
  - 2342/tcp  # Photoprism
  - 5353/udp  # bonjour / avahi network discovery
  - 8000/tcp  # portainer
  - 8001/tcp  # paperless-ngx
  - 8008/tcp  # nextcloud dashboard
  - 8080/tcp  # homer dashboard
  - 8096/tcp  # jellyfin
  - 8123/tcp  # home assistant
  - 8324/tcp  # plex for roku (optional)
  - 8384/tcp  # syncthing
  - 8888/tcp  # nginx dashboard
  - 9000/tcp  # portainer dashboard
  - 9091/tcp  # transmission
  - 11111/tcp # freshrss
  - 19999/tcp   # netdata dashboard
  - 22000/tcp   # syncthing
  - 22000/udp   # syncthing
  - 21027/udp   # syncthing
  - 32400/tcp   # Plex Media Server
  - 32410/udp   # current GDM network discovery
  - 32469/tcp   # Plex DLNA Server
  - 51413/tcp   # transmission
  - 51413/udp   # transmission
  - 61208/tcp   # glances
  - 61209/tcp   # glances

services:
  - dns
  - ftp
  - grafana
  - http
  - https
  - nfs
  - plex
  - rsyncd
  - ssh
  - transmission-client

#### Secrets in vault.yml (add to vault.yml)

# password: ""
# user: ""
# group: "{{ user }}"
# ssh_port: ""
