# User settings
uid: "1001"
gid: "1001"
shell: /bin/zsh
sudo_group: wheel

# Locale
timezone: Europe/Zurich
domain_name: manickathan.ch

# Install packages
packages:
  - curl
  - git
  - htop
  - neofetch
  - nmap
  - python3-pip
  - rsync
  - tmux
  - tree
  - wget
  - zsh

# Install python packages
python_packages:
  - pip
  - pipx

# Install user python packages
python_user_packages:
  - docker
  - docker-compose

# Docker
docker_users:
  - "{{ user }}"

storage_dir: "/opt/data"

# Docker volumes
docker_dir: "{{ storage_dir }}/docker"

tv_dir: "{{ storage_dir }}/media/tv"
movies_dir: "{{ storage_dir }}/media/movies"

# Ports (tcp, udp)
ports:
  # - 22/tcp    # ssh (disabled)
  - 53/tcp    # dns (pi-hole)
  - 53/udp    # dns (pi-hole)
  - 80/tcp    # http
  - 81/tcp    # pi-hole dashboard
  - 443/tcp   # https
  - 1900/udp  # Plex DLNA Server
  - 5353/udp  # bonjour / avahi network discovery
  - 8000/tcp  # portainer
  - 8080/tcp  # homer dashboard
  - 8324/tcp  # plex for roku (optional)
  - 8888/tcp  # nginx dashboard
  - 9000/tcp  # portainer dashboard
  - 32400/tcp   # Plex Media Server
  - 32410/udp   # current GDM network discovery
  - 32469/tcp   # Plex DLNA Server

services:
  - dns
  - ftp
  - grafana
  - http
  - https
  - plex
  - rsyncd
  - ssh
  - transmission-client

#### Secrets in vault.yml (add to vault.yml)

# password: ""
# user: ""
# group: "{{ user }}"
# ssh_port: ""
