# User settings
user: lento
group: "{{ user }}"
uid: 1001
gid: 1001
shell: /bin/zsh
sudo_group: wheel

# Install packages
packages:
  - curl
  - git
  - htop
  - neofetch
  - nginx
  - nmap
  - python3-pip
  - python3-firewall
  - rsync
  - tmux
  - tree
  - wget
  - zsh

# Install python packages
python_packages:
  - pip
  - pipx

# Install user python packages
python_user_packages:
  - docker
  - docker-compose

# Docker
docker_users:
  - "{{ user }}"

# Ports (tcp, udp)
ports:
  - 22/tcp    # ssh
  - 80/tcp    # http
  - 443/tcp   # https
  - 8000/tcp  # portainer
  - 9000/tcp  # portainer

# Secrets in vault.yml
password: ''
