- name: Install nfs
  become: true
  dnf:
    name: nfs-utils
    state: latest

- name: Add nfs folder to exports
  become: true
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: Restart nfs
