- name: Setup auto updates using dnf-automatic
  become: true
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present

- name: Ensure auto updates are enabled
  become: true
  ansible.builtin.service:
    name: dnf-automatic-install.timer
    enabled: true
    state: started
