- name: Install avahi-daemon and dependencies in redhat
  become: true
  ansible.builtin.dnf:
    name:
      - nss-mdns
      - avahi
    state: present
  notify:
    - Restart avahi
  when: ansible_os_family == 'RedHat'

- name: Install avahi-daemon and dependencies in debian
  become: true
  ansible.builtin.apt:
    name:
      - avahi-daemon
    state: present
  notify:
    - Restart avahi
  when: ansible_os_family == 'Debian'
