- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: true

- name: Ensure autossh service is running
  become: true
  service:
    name: autossh
    state: restarted
    enabled: true
