- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure autossh service is running
  become: true
  ansible.builtin.service:
    name: autossh
    state: restarted
    enabled: true
