- name: Deploy Pi-hole
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:latest
    env:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ pihole_password }}"
      # ServerIP: "{{ ansible_default_ipv4.address }}"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80/tcp"
    volumes:
      - "{{ docker_dir }}/pihole/etc-pihole:/etc/pihole"
      - "{{ docker_dir }}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    privileged: true
    hostname: "{{ inventory_hostname }}"
    domainname: "heimdall"
    restart_policy: always

- name: Copy custom local DNS domains to pihole
  become: true
  template:
    src: custom.list.j2
    dest: "{{ docker_dir }}/pihole/etc-pihole/custom.list"
    mode: "0644"
  notify: Restart pihole
