- name: Add user {{ user }}
  become: true
  user:
    name: "{{ user }}"
    uid: "{{ uid }}"
    shell: "{{ shell }}"
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - "{{ group }}"
      - users
    append: true

- name: Ensure group "{{ user }}" exists
  group:
    name: "{{ user }}"
    state: present
