- name: Install firewalld
  become: true
  dnf:
    name: firewalld
    state: present

- name: Configure ports in firewalld
  become: true
  ansible.posix.firewalld:
    state: enabled
    port: "{{ item }}"
    zone: public
    permanent: true
    immediate: true
  with_items:
    - "{{ ports }}"
  notify: Restart firewalld
