- name: "Include redhat tasks"
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'

- name: "Include debian tasks"
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family|lower == 'debian'

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  become: true
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists
