- name: Update dnf packages
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: "*"
    state: latest

- name: Autoremove unneeded dnf packages
  become: true
  ansible.builtin.dnf:
    autoremove: true
