- name: Deploy nextcloud-mariadb
  community.docker.docker_container:
    name: nextcloud-mariadb
    image: mariadb
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed --innodb-read-only-compressed=OFF"
    volumes:
      - "{{ docker_dir }}/nextcloud/db:/var/lib/mysql"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      TZ: "{{ timezone }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
    restart_policy: unless-stopped


- name: Deploy nextcloud
  community.docker.docker_container:
    name: nextcloud
    image: nextcloud
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      TZ: "{{ timezone }}"
      ServerName: "{{ ansible_hostname }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_HOST: "nextcloud-mariadb"
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.{{ domain_name }}"
    volumes:
      - "{{ docker_dir }}/nextcloud/nextcloud:/var/www/html"
    ports:
      - "8008:80/tcp"
    links:
      - nextcloud-mariadb
    restart_policy: unless-stopped

- name: Add trusted domains
  become: true
  lineinfile:
    path: "{{ docker_dir }}/nextcloud/nextcloud/config/config.php"
    insertafter: "0 => '{{ ansible_hostname }}.{{ domain_name }}:8008'"
    line: "          1 => 'nextcloud.{{ domain_name }}',"
