- name: Playbook to manage all infra
  hosts: homelab

  roles:
    # Add default user
    # - users

    - upgrade
    - packages

    # Install docker
    # - role: geerlingguy.docker
    #   become: true
    #   vars:
    #     docker_users:
    #       lento
