- name: Deploy wireguard
  community.docker.docker_container:
    name: wireguard
    image: lscr.io/linuxserver/wireguard
    capabilities:
      - NET_ADMIN
      - SYS_ADMIN
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      SERVERPORT: "51820"
      PEERS: "1"
      PEERDNS: "auto"
      ALLOWEDIPS: "0.0.0.0/0"
    volumes:
      - "{{ docker_dir }}/wireguard/config:/config"
      - lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart_policy: unless-stopped
