- name: Deploy Portainer
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ docker_dir }}/portainer:/data"
    restart_policy: always
